version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Setup
          command: apt-get install gcc-arm-none-eabi
      - run:
          name: Build
          command: make
