version: 2
jobs:
  build:
    docker:
      - image: debian:jessie
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Setup
          command: |
            apt-get update
            apt-get install -y gcc-arm-none-eabi
      - run:
          name: Build
          command: |
            cd "Dive Computer"
            make
